### ISSUE TITLE
lua-binding for kazmath

### ISSUE THREAD

**Issue by rocaltair** [Kazade/kazmath#40]
hi~ @Kazade 
I forked this
[lua-binding](https://github.com/rocaltair/kazmath)

so far so good.

* add all functions for kazmath/*.h (except kazmath/GL/*.h)
* lkazmath.km* for all functions
* use lkazmath.*New or lkazmath.*NewWithArray or lkazmath.*NewWithTbl to create a object (struct in C)
* method ToArray, ToTbl for vec*, mat*
* OOP support (without prefix km${StructName}), for example 
```
mat3 = lkazmath.kmMat3New()
mat3:ToArray()
```
or you can use
```
lkazmath.kmMat3ToArray(mat3)
```
* alter args(such as kmScalar *out are removed from function params), see lua__kmMat4RotationToAxisAngle, lua__kmLine2WithLineIntersection

**Comment by Kazade** [comment]
That's great! I'd happily accept a pull request when you are done. Also the C89 fixes would be appreciated! :)

**Comment by rocaltair** [comment]
I'd be happy to.
Most of them are completed now, I need more tests before the pull request.
:)
