### ISSUE TITLE
Minor CMake issue?

### ISSUE THREAD

**Issue by AthulJP** [Kazade/kazmath#46]
I'm getting an error in CMake while building. It says it requires "language dialect C89" but that CMake doesn't know the compile flags for it.

As far as I can tell CMake only supports C90, C99 and C11 for CMAKE_C_STANDARD.Is it ok if I change it to C99? C89 and 90 apparently don't support single line '//' comments and I saw a whole bunch of those in the project.

While I'm at it, I wanted to add an option to build shared libs for CMake-gui and a pkg-config file. Any interest?

**Comment by jacmoe** [comment]
I changed it to 99, but I think the intention was to set it to 90 instead of 99.
See the latest change to the main CMake script.
